[2025-01-17T07:37:41.229+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_data_etl_workflow.fetch_movie_data manual__2025-01-17T07:37:40.184668+00:00 [queued]>
[2025-01-17T07:37:41.250+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_data_etl_workflow.fetch_movie_data manual__2025-01-17T07:37:40.184668+00:00 [queued]>
[2025-01-17T07:37:41.250+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-01-17T07:37:41.270+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): fetch_movie_data> on 2025-01-17 07:37:40.184668+00:00
[2025-01-17T07:37:41.275+0000] {standard_task_runner.py:57} INFO - Started process 66 to run task
[2025-01-17T07:37:41.280+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movie_data_etl_workflow', 'fetch_movie_data', 'manual__2025-01-17T07:37:40.184668+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmpaz782obb']
[2025-01-17T07:37:41.281+0000] {standard_task_runner.py:85} INFO - Job 251: Subtask fetch_movie_data
[2025-01-17T07:37:41.301+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-17T07:37:41.347+0000] {task_command.py:415} INFO - Running <TaskInstance: movie_data_etl_workflow.fetch_movie_data manual__2025-01-17T07:37:40.184668+00:00 [running]> on host 1d5d3d5ac065
[2025-01-17T07:37:41.455+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='movie_data_etl_workflow' AIRFLOW_CTX_TASK_ID='fetch_movie_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T07:37:40.184668+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T07:37:40.184668+00:00'
[2025-01-17T07:37:41.458+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-17T07:37:41.459+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/DE_project/ETL/extract/API_movie_Themoviedb.py']
[2025-01-17T07:37:41.472+0000] {subprocess.py:86} INFO - Output:
[2025-01-17T07:38:47.217+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-01-17T07:38:47.228+0000] {process_utils.py:131} INFO - Sending 15 to group 66. PIDs of all processes in the group: [67, 66]
[2025-01-17T07:38:47.230+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 66
[2025-01-17T07:38:47.233+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-17T07:38:47.235+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-01-17T07:38:47.332+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=67, status='terminated', started='07:37:40') (67) terminated with exit code None
[2025-01-17T07:38:47.333+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=66, status='terminated', exitcode=0, started='07:37:40') (66) terminated with exit code 0
