[2024-12-23T07:48:52.419+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-12-23T07:48:52.434+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_data_workflow.analyze_data scheduled__2024-12-22T00:00:00+00:00 [queued]>
[2024-12-23T07:48:52.444+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_data_workflow.analyze_data scheduled__2024-12-22T00:00:00+00:00 [queued]>
[2024-12-23T07:48:52.445+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-23T07:48:52.458+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): analyze_data> on 2024-12-22 00:00:00+00:00
[2024-12-23T07:48:52.464+0000] {standard_task_runner.py:57} INFO - Started process 64 to run task
[2024-12-23T07:48:52.468+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movie_data_workflow', 'analyze_data', 'scheduled__2024-12-22T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmpp4vn80fh']
[2024-12-23T07:48:52.469+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask analyze_data
[2024-12-23T07:48:52.488+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T07:48:52.531+0000] {task_command.py:415} INFO - Running <TaskInstance: movie_data_workflow.analyze_data scheduled__2024-12-22T00:00:00+00:00 [running]> on host 023362aefa72
[2024-12-23T07:48:52.547+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-12-23T07:48:52.616+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='movie_data_workflow' AIRFLOW_CTX_TASK_ID='analyze_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-22T00:00:00+00:00'
[2024-12-23T07:48:52.618+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-23T07:48:52.619+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'papermill /opt/***/DE_project/DA/DataAnalysis.ipynb /opt/***/DE_project/DA/DataAnalysis_output.ipynb']
[2024-12-23T07:48:52.629+0000] {subprocess.py:86} INFO - Output:
[2024-12-23T07:48:52.633+0000] {subprocess.py:93} INFO - /bin/bash: line 1: papermill: command not found
[2024-12-23T07:48:52.633+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-12-23T07:48:52.648+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-23T07:48:52.655+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=movie_data_workflow, task_id=analyze_data, execution_date=20241222T000000, start_date=20241223T074852, end_date=20241223T074852
[2024-12-23T07:48:52.668+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 27 for task analyze_data (Bash command failed. The command returned a non-zero exit code 127.; 64)
[2024-12-23T07:48:52.689+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-23T07:48:52.709+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
